version: "3.7"
services:
    # imagem micro 01
    micro_01:
        build:
            args:
                user: dprado
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        container_name: app_micro_01
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis_micro_01
            - queue
        networks:
            - microservices

    # nginx
    nginx:
        image: nginx:alpine
        container_name: nginx_micro_01
        restart: unless-stopped
        ports:
            - 8000:80
            - 444:443
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - microservices

    # mysql micro 01
    db_micro_01:
        image: mysql:5.7.22
        container_name: mysql_micro_01
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - 3309:3306
        networks:
            - microservices

    # queue micro 01
    queue:
        build:
            args:
                user: dprado
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        container_name: queue_micro_01
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes:
            - ./:/var/www
        depends_on:
            - redis_micro_01
        networks:
            - microservices

    #redis
    redis_micro_01:
        image: redis:latest
        container_name: redis_micro_01
        networks:
            - microservices

networks:
    microservices:
        driver: bridge
